"""add invoice detail fields

Revision ID: 8bd1dbb125a7
Revises: 24e8bd9d46f1
Create Date: 2026-03-24 14:57:59.213153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd1dbb125a7'
down_revision: Union[str, None] = '24e8bd9d46f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('uploader_name', sa.String(length=128), nullable=True))
    op.add_column('expenses', sa.Column('uploader_dept', sa.String(length=64), nullable=True))
    op.add_column('expenses', sa.Column('submitter_dept', sa.String(length=64), nullable=True))
    op.add_column('expenses', sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('expenses', sa.Column('expense_date', sa.Date(), nullable=True))
    op.add_column('expenses', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('seller_tax_id', sa.String(length=16), nullable=True))
    op.add_column('expenses', sa.Column('seller_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'seller_name')
    op.drop_column('expenses', 'seller_tax_id')
    op.drop_column('expenses', 'tax_amount')
    op.drop_column('expenses', 'net_amount')
    op.drop_column('expenses', 'total_amount')
    op.drop_column('expenses', 'expense_date')
    op.drop_column('expenses', 'upload_date')
    op.drop_column('expenses', 'submitter_dept')
    op.drop_column('expenses', 'uploader_dept')
    op.drop_column('expenses', 'uploader_name')
    # ### end Alembic commands ###
